name: CI
on:
  push:
    branches:
    - sharks-king-patch-1
#    paths:
#    - docker-build
jobs:
  docker-build:
    name: docker-build
    runs-on: ubuntu-latest
    
    steps:
    - name: Environmental inspections 
      run: | 
        tree
        ls
        docker version
        docker compose version
