name: CI
on:
  push:
    branches:
    - main
    paths:
    - docker-build
jobs:
  docker-build:
    name: docker-build
    runs-on: ubuntu-latest
    
    steps:
      run: | 
        ls
        docker version
        docker compose version
      
    
