name: CI
on:
  push:
    branches:
    - sharks-king-patch-1
#    paths:
#    - docker-build/*
jobs:
  docker-build:
    name: docker-build
    runs-on: ubuntu-latest
    
    steps:
    - name: code pul
      uses: actions/checkout@v4
      
    - name: Environmental inspections
      run: | 
        docker version
        docker compose version
        pwd
        ls ./
        echo 0
        ls ../
        echo 1
        ls ../../
        echo 3

    - name: docker build
      run: |
       cd docker-build
       bash -x build.sh 
